services:
  jekyll:
    image: docker.io/jekyll/jekyll:latest
    command: bash -c "bundle install && bundle exec jekyll serve --livereload --force_polling -H 0.0.0.0 -P 4001"
    volumes:
      - ./:/srv/jekyll:Z
      - bundle_cache:/usr/local/bundle
    ports:
      - "4001:4001"
      - "35729:35729"

volumes:
  bundle_cache:
