name: PR Quality Check

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint --format github .

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"

  build:
    needs: [lint-yaml, lint-markdown]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Merge single YAML data files
        run: |
          mkdir -p _data
          for dir in _data/single/*/ ; do
            foldername=$(basename "$dir")
            shopt -s nullglob
            files=("$dir"*.yml)
            if [ "${#files[@]}" -eq 0 ]; then
              echo "No YAML files found in $dir, skipping."
              continue
            fi
            
            if [ "$foldername" = "members" ]; then
              output="_data/members_units.yml"
              echo "FILE ${output}"
              echo "Auto-merged from _data/single/${foldername}/*.yml"
              echo "# Auto-merged from _data/single/${foldername}/*.yml" > "$output"

              echo "units:" > "$output"
              
              for file in "$dir"*.yml; do
                filename=$(basename "$file")
                echo "" >> "$output"
                echo "From file: $filename"  
                echo "## From file: $filename" >> "$output"
                echo "  -" >> "$output"
                
                # Indent each line by 2 spaces and append to output
                sed 's/^/    /' "$file" >> "$output"
                
                echo "" >> "$output"
              done

            else
              output="_data/${foldername}.yml"
              echo "FILE ${output}"
              echo "Auto-merged from _data/single/${foldername}/*.yml"
              echo "# Auto-merged from _data/single/${foldername}/*.yml" > "$output"

              for file in "$dir"*.yml; do
                filename=$(basename "$file")
                echo "" >> "$output"
                echo "From file: $filename"
                echo "## From file: $filename" >> "$output"
                cat "$file" >> "$output"
              done
              echo "" >> "$output"
            fi
          done

      - name: Jekyll Build Check
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
